stages:
    - test
    - build
    - release

variables:
    CONTAINER_IMAGE: "registry.ely.by/elyby/accounts"

php-cs-fixer:
    image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
    stage: test
    cache:
        key: backend-vendor
        paths:
            - vendor
    script:
        - composer install
        - vendor/bin/php-cs-fixer fix -v --dry-run

codeception:
    image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
    services:
        - name: redis:4.0.10-alpine
          alias: redis
        - name: mariadb:10.2.11
          alias: db
    variables:
        # App config
        DB_HOST: "db"
        DB_DATABASE: "ely_accounts_test"
        DB_USER: "ely_accounts_tester"
        DB_PASSWORD: "ely_accounts_tester_password"
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        # MariaDB config
        MYSQL_RANDOM_ROOT_PASSWORD: "true"
        MYSQL_DATABASE: "ely_accounts_test"
        MYSQL_USER: "ely_accounts_tester"
        MYSQL_PASSWORD: "ely_accounts_tester_password"
    stage: test
    cache:
        key: backend-vendor
        paths:
            - vendor
    before_script:
        # While we not counting coverage, xdebug only slow down tests
        - sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    script:
        - composer install
        - php yii rbac/generate
        - ./docker/php/wait-for-it.sh "${DB_HOST}:3306" -s -t 0 -- "php yii migrate/up --interactive=0"
        - vendor/bin/codecept run

build:production:
    image: docker:18.02
    stage: build
    before_script:
        - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
        - export VERSION="${CI_COMMIT_TAG:-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:7}}"
        - echo "$SSH_PRIVATE_KEY" > id_rsa
        - sed -i"" -e "s/{{PLACE_VERSION_HERE}}/$VERSION/g" common/config/config.php
    script:
        - export IMAGE_NAME="$CONTAINER_IMAGE:latest"
        - docker build --pull --build-arg build_env=prod -t $IMAGE_NAME .
    only:
        - develop
        - tags

release:latest:
    image: docker:18.02
    stage: release
    variables:
        GIT_STRATEGY: none
    before_script:
        - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
    script:
        - docker push $CONTAINER_IMAGE:latest
    only:
        - develop
        - tags

release:tag:
    image: docker:18.02
    stage: release
    variables:
        GIT_STRATEGY: none
    before_script:
        - docker login -u gitlab-ci -p $CI_BUILD_TOKEN registry.ely.by
    script:
        - export IMAGE_NAME="$CONTAINER_IMAGE:$CI_BUILD_TAG"
        - docker tag $CONTAINER_IMAGE:latest $IMAGE_NAME
        - docker push $IMAGE_NAME
    only:
        - tags
