version: '2'
services:
    app:
        build: .
        links:
            - db
            - redis
            - rabbitmq
        depends_on:
            - app-console-account-queue
        volumes:
            - ./:/var/www/html/
        env_file: .env

    web:
        build: ./docker/nginx
        links:
            - app
        volumes_from:
            - app
        environment:
            - AUTHSERVER_HOST=authserver.ely.by
            - PHP_LINK=app

    node-dev-server:
        build: ./frontend
        ports:
            - "8080:8080"
        volumes:
            - ./frontend/:/usr/src/app/
        environment:
            DOCKERIZED: "true"

    app-console-account-queue:
        build: .
        volumes:
            - ./:/var/www/html/
        command: ./docker/wait-for-it.sh rabbitmq:5672 -- ./yii account-queue
        links:
            - db
            - redis
            - rabbitmq

    db:
        build: ./docker/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "ely_accounts"
            MYSQL_USER: "ely_accounts_user"
            MYSQL_PASSWORD: "ely_accounts_password"

    redis:
        image: redis:3.0

    rabbitmq:
        build: ./docker/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "ely-accounts-app"
            RABBITMQ_DEFAULT_PASS: "ely-accounts-app-password"
            RABBITMQ_DEFAULT_VHOST: "/ely.by"
        ports:
            - "15672:15672" # Manager interface

    phpmyadmin:
        build: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=
        ports:
            - "8181:80"
        links:
            - db
