version: '2'
services:
    app:
        build:
            dockerfile: Dockerfile-dev
            context: .
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - ./:/var/www/html/
        env_file: .env

    web:
        build: ./docker/nginx
        volumes_from:
            - app
        links:
            - app:php
        env_file: .env
        networks:
            - default
            - nginx-proxy

    db:
        build: ./docker/mariadb
        env_file: .env
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis:3.0-alpine
        volumes:
            - ./data/redis:/data

    rabbitmq:
        image: rabbitmq:3.6-management
        env_file: .env
        environment:
            - VIRTUAL_HOST=rabbitmq.account.ely.by.local
            - VIRTUAL_PORT=15672
        networks:
            - default
            - nginx-proxy

    phpmyadmin:
        build: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=
            - VIRTUAL_HOST=pma.account.ely.by.local
        depends_on:
            - db
        networks:
            - default
            - nginx-proxy

    # Эта штука работает дико медленно, грузит процессор и т.д. и т.п.
    # Раскоментировать только в случае лютой надобности
    #node-dev-server:
    #    build: ./frontend
    #    ports:
    #        - "8080:8080"
    #    volumes:
    #        - ./frontend/:/usr/src/app/
    #    environment:
    #        DOCKERIZED: "true"

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
