version: '2'
services:
    app:
        image: registry.ely.by/elyby/accounts:latest
        depends_on:
            - db
            - redis
            - rabbitmq
        env_file: .env

    web:
        image: registry.ely.by/elyby/accounts-nginx:1.0.2
        volumes_from:
            - app
        links:
            - app:php
        env_file: .env
        networks:
            - default
            - nginx-proxy

    db:
        build: ./docker/mariadb
        env_file: .env
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis:3.0-alpine
        volumes:
            - ./data/redis:/data

    rabbitmq:
        image: rabbitmq:3.6
        env_file: .env

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
