version: '2'
services:
    app:
        build: .
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - ./:/var/www/html/
        env_file: .env

    web:
        build: ./docker/nginx
        volumes_from:
            - app
        links:
            - app:php
        env_file: .env
        networks:
            - default
            - nginx-proxy

    node-dev-server:
        build: ./frontend
        ports:
            - "8080:8080"
        volumes:
            - ./frontend/:/usr/src/app/
        environment:
            DOCKERIZED: "true"

    app-console-account-queue:
        build: .
        volumes:
            - ./:/var/www/html/
        command: ["docker/wait-for-it.sh", "rabbitmq:5672", "--", "php", "yii", "account-queue"]
        links:
            - db
            - redis
            - rabbitmq

    db:
        build: ./docker/mariadb
        env_file: .env

    redis:
        image: redis:3.0

    rabbitmq:
        build: ./docker/rabbitmq
        env_file: .env
        ports:
            - "15672:15672" # Manager interface

    phpmyadmin:
        build: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=
        ports:
            - "8181:80"
        depends_on:
            - db

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
